"""
Validation codes for the Resume Validator.

All validation logic must reference these codes instead of raw string literals.
"""

from enum import Enum


class ValidationCode(str, Enum):
    """Strongly typed validation codes used by the ResumeValidator."""

    # Structural / required fields
    MISSING_CONTACT = "MISSING_CONTACT"
    MISSING_SUMMARY = "MISSING_SUMMARY"
    MISSING_SKILLS = "MISSING_SKILLS"
    MISSING_EXPERIENCE = "MISSING_EXPERIENCE"
    MISSING_PROJECTS = "MISSING_PROJECTS"
    MISSING_EDUCATION = "MISSING_EDUCATION"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"

    # Count constraints
    INVALID_EXPERIENCE_COUNT = "INVALID_EXPERIENCE_COUNT"
    INVALID_PROJECT_COUNT = "INVALID_PROJECT_COUNT"
    INVALID_SKILL_CATEGORY_COUNT = "INVALID_SKILL_CATEGORY_COUNT"
    INVALID_EDUCATION_COUNT = "INVALID_EDUCATION_COUNT"

    # Entity integrity
    DUPLICATE_ENTITY_ID = "DUPLICATE_ENTITY_ID"
    EMPTY_HIGHLIGHTS = "EMPTY_HIGHLIGHTS"
    EMPTY_TECHNOLOGIES = "EMPTY_TECHNOLOGIES"
    EMPTY_DOMAINS = "EMPTY_DOMAINS"
    EMPTY_SKILLS = "EMPTY_SKILLS"
    DUPLICATE_SKILL = "DUPLICATE_SKILL"
    MISSING_ENTITY_ID = "MISSING_ENTITY_ID"

    # Immutable field violations
    MODIFIED_IMMUTABLE_FIELD = "MODIFIED_IMMUTABLE_FIELD"

    # Entity source
    INVALID_SOURCE = "INVALID_SOURCE"
    MISSING_SOURCE = "MISSING_SOURCE"

    # Warnings
    SUMMARY_TOO_SHORT = "SUMMARY_TOO_SHORT"
    SUMMARY_TOO_LONG = "SUMMARY_TOO_LONG"
    TOO_MANY_EXPERIENCE_HIGHLIGHTS = "TOO_MANY_EXPERIENCE_HIGHLIGHTS"
    TOO_MANY_PROJECT_HIGHLIGHTS = "TOO_MANY_PROJECT_HIGHLIGHTS"
    EMPTY_SKILL_CATEGORY = "EMPTY_SKILL_CATEGORY"
