"""
Domain models for the Job Description Analyzer.

JobAnalysis is a pure data container representing the structured output
of analyzing a raw job description.
No scoring, recommendations, or AI reasoning is included.
"""

from typing import List, Optional
from pydantic import BaseModel, ConfigDict, Field


class JobAnalysis(BaseModel):
    """
    Structured representation of a analyzed job description.

    Contains only information required by downstream resume generation.

    Every field is extracted verbatim from the job description. There is
    deliberately no free-text field: prose generated by the model is the
    least reproducible part of an analysis, and this model is required to
    be deterministic for a given job description.
    """

    model_config = ConfigDict(
        extra="forbid",
        validate_assignment=True,
    )

    company: Optional[str] = None
    role: str = Field(min_length=1)
    seniority: Optional[str] = None
    required_skills: List[str]
    preferred_skills: List[str] = []
    technologies: List[str] = []
    domains: List[str] = []
    responsibilities: List[str] = []
    qualifications: List[str] = []
    nice_to_have: List[str] = []
    keywords: List[str]
